### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by mixmix** [jdholtz/i3-restore#1]
Hi, thanks for putting the work into this.
I've had trouble installing on Ubuntu 22.04 (specifically Regolith-Desktop which uses that Ubuntu as a base)

I followed all the install instructions I think, but have hit this error:

```bash
./i3-save.sh 
./i3-save.sh: line 36: /home/mixusername/.config/i3/workspace_2:<span font_desc="BitstreamVeraSansMono Nerd Font 12"> 2 </span>_layout.json: No such file or directory
```

I've ensured there is a folder `~/.config/i3` but that hasn't helped
Any pointers most appreciated :heart: :pineapple:

**Comment by jdholtz** [comment]
Hi. Thanks for filing this issue! 

What is the name of your 2nd workspace? It appears that you have specified special text for the name. I will try to reproduce the error and fix it by using  the name of that workspace.

**Comment by jdholtz** [comment]
Hello @mixmix. I was able to replicate your issue with the information you provided. I switched to a new method when saving workspaces, so hopefully custom workspace names won't be an issue anymore. Can you confirm that this change works by using this branch - https://github.com/jdholtz/i3-restore/tree/save_ws_by_number?

**Comment by jdholtz** [comment]
Hey @mixmix. I have successfully fixed this issue. The problem is that you cannot save a file with a slash. Therefore, I just replaced the slash with a placeholder when saving the file. Can you test [this](https://github.com/jdholtz/i3-restore/tree/slash_in_ws_name) branch to make sure it works correctly for you?

**Comment by mixmix** [comment]
Thank you! I'll test this when I next have a chance and let you know

**Comment by jdholtz** [comment]
Hey @mixmix. Were you able to give this a try yet?

**Comment by mixmix** [comment]
![signal-2022-08-12-16-40-30-675.png](https://user-images.githubusercontent.com/2665886/184286245-4e1d1534-1b44-43af-aa8e-bf6c1287ebd6.png)

Hooray! It managed to open a bunch of things. Like signal, a terminal in the right place, browser with right tabs. It does make these artifacts and in one case failed to open a terminal. Any ideas?

Also please don't feel a need to fix this in any hurry. I would love this, but can totally live without

**Comment by jdholtz** [comment]
Gals it worked!

I have had that issue with messaging systems that take a long time to start up (Discord and Slack). It has to do with i3 not swallowing the window because the window title is different when it starts. 

I have an idea on how to fix that so I’ll try to implement that soon

**Comment by mixmix** [comment]
Oh cool, that's good to know. I am running alacrity as a terminal.... But that should be fast to start up. Unless neovim startup is messing with it?

**Comment by jdholtz** [comment]
Sometimes what can happen is that the window title might be different when it is saved. For example, Alacritty changes the title when you ssh (by default). When the terminal starts up again, the window title will be Alacritty. So, after its initial startup, I’ll need to make it start  looking by window class instead of title. That’s why it isn’t always restoring exactly correct at the moment.
