### ISSUE TITLE
README: please add about root terminal windows

### ISSUE THREAD

**Issue by vitaly-zdanevich** [jdholtz/i3-restore#13]
### Description

Hi, I did not try this software yet (but I will try, thanks for your work), but I think that this is impossible to restore a terminal window after `su` command? Anyway, for new visitors, I think this is a good to mention in the README.

Side note: I added this to Gentoo GURU https://github.com/gentoo/guru/tree/master/x11-misc/i3-restore

**Comment by jdholtz** [comment]
It does work with `su`, if you have it in the configuration (and it is there by default). However, it doesn't restore to the correct window when you have a dynamic terminal title (such as in kitty) because you obviously need to type in a password first for the terminal title to match. I can add this to the Readme as a limitation.

Thanks for adding this to Gentoo Guru!

**Comment by jdholtz** [comment]
Added a new limitations section in the Readme for this. Thanks!
