### ISSUE TITLE
Minor potential readme issue

### ISSUE THREAD

**Issue by pbower** [jdholtz/i3-restore#18]
### Description

Hi there,

There is a line in the README that states:

exec /path/to/i3-restore/i3-restore --interval <minutes>
for saving the files.

Should this be:

exec /path/to/i3-restore/i3-save --interval <minutes>

?

I thought I'd bring this to your attention.

Looking forward to using the plugin.

Thanks,
Pete

### To Reproduce

Go to README file

### Version

N/A

### Additional context

Likely typo, or otherwise embedded arguments within the script that may be counter-intuitive, but if so I apologise. Thanks.

**Comment by jdholtz** [comment]
Hey, thanks for filing this. This documentation is actually intended. The `--interval` flag is documented in the Readme [here](https://github.com/jdholtz/i3-restore?tab=readme-ov-file#restoring). 

I do see how this could be confusing as it is run using the i3-restore script instead of i3-save and am open to suggestions to make it less confusing. This flag is documented in both the Readme and the help menu of the i3-restore script (`./i3-restore --help`).

**Comment by jdholtz** [comment]
The flag was changed from `--interval` to `--save-interval` in v4.3 to clear up confusion. Here's the link to the [changelog](https://github.com/jdholtz/i3-restore/blob/master/CHANGELOG.md#43-2024-08-11) for v4.3.
